<a href="https://colab.research.google.com/github/laya7171/DS_Repo/blob/main/introduction/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to numpy


*   Creating array✅
*   Multidiimensional array
*   Randomly generated arrays
*   Element wise operations
*   Summarize operations










Single dimensional arrays

In [17]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
#creating an array of size 10 with all elements 3
np.full(3, 4)

array([4, 4, 4])

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
#create an array with evenly spaced numbers within a specified range
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multidimensional Array


In [18]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
a[0,1]= 20

In [51]:
a

array([[ 1, 20,  1],
       [ 1,  1,  1],
       [ 1,  1,  1]])

In [55]:
a[2]= 1

In [56]:
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [59]:
a[:,2]=[2,2,2]

In [60]:
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 2,  2,  2]])

In [69]:
b=np.full((3,3),10)

In [70]:
b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [66]:
b

array([10, 10])

### Randomly generated array

-Numpy can create arrays filled with random numbers
-To ensure the reproducibility, you can set a seed using ```np.random.seed().It will generayte the exact same random numbers for each executions.
-If you remove or change the seed values, the sequence of random numbers will be changed.

In [78]:
np.random.seed(5)
np.random.rand(4)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091])

In [80]:
np.random.randn(5,2)

array([[ 2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651]])

In [85]:
np.random.randint(3,5,(5,5))

array([[4, 4, 4, 4, 3],
       [3, 3, 4, 4, 4],
       [3, 4, 4, 4, 3],
       [3, 4, 3, 3, 4],
       [4, 4, 3, 4, 4]])